### ISSUE TITLE
As a user I should be able to bind services to applications

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#160]
## Acceptance Criteria
The user should be able to:

- Provision services
- Bind services to applications.
  This should make the service information (e.g. credentials) accessible to the application code somehow (e.g. env var or secret mounted as files).
- See what services an application has attached
- Unbind services from applications
- List service (bound or non-bound)

**Comment by agracey** [comment]
I think I already made this comment elsewhere. Sorry for the duplication...

Whatever is done, let's not use VCAP_SERVICES as the mechanism to pass in the binding params. It's painful to parse and use.

**Comment by agracey** [comment]
And I'll take the work of changing samples to use a new format if needed!

**Comment by jimmykarily** [comment]
Yes I remember: https://github.com/scf-samples/rails-example/blob/master/config/database.yml#L6 :D !
The format is not yet defined but some parsing will be needed, that's for sure. For some services we don't even know the structure of the service information. Usually it's something like host, port, username, password but it could differ, so we can't make it too easy. Let's see what this implementation brings and we can iterate.

**Comment by agracey** [comment]
Totally. Something is needed but just not near as complicated 😄

**Comment by andreas-kupries** [comment]
# Using secrets

  - https://kubernetes.io/docs/concepts/configuration/secret/
  - https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

  1. Choose name of service as the name for the secret, volume, and volume mount
  2. Services are namespaced - Linked to a org, like an app belongs to an org.
  3. Secrets are namespaced. Example is unclear about if I can reference a secret outside the namespace the app runs in.
       - So, for new keep secrets in the `carrier-workloads` namespace.
         Ensure, by name, that service secrets cannot conflict with carrier system secrets.
         => Secret names have prefix `service.`
       - Impose partioning for orgs on the secrets, by using the org name as additional prefix.
         We are doing the same already for app.
  4. Note, it is not the pod we have to modify. It will be the `spec.template` in the controlling deployment resource.

With the changes the pod (template) from the example in the second link will look more like:

```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
*   volumeMounts:
*   - name: ((service-name))
*     mountPath: "/services/((service-name))"
*     readOnly: true
* volumes:
* - name: ((service-name))
*   secret:
*     secretName: "service.((org-name)).((service-name))"
```

Each service would be a separate secret.

# Structure of secrets

  - Binding information usually is a dictionary of keys and values, with keys for example `host`, `password`, `port`, etc.
  - Map the keys in the binding information to keys in the secret.
    In the container the keys appear as files, which contain the value.
    I.e., using the example above, a key `host` would appear as path `/services/((service-name))/host`. Etc.

# Commands

  1. CUPS - Custom User Provided Service.
      Just provide the service name and the binding information.
      Could be a single argument, a json blob. Carrier would decode that and generate a matching secret.
      And/or multiple arguments, keys and values...

     `carrier service custom ((name)) ((key value))...`

  2. Binding service by name. Locate secret, then modify the pod template in the deployment.

      `carrier service bind ((service-name)) ((app-name))`
      `carrier app bind ((app-name)) ((service-name))`

**Comment by andreas-kupries** [comment]
Some more thoughts on this ...

- The secret I currently use to represent the service is also the binding information. This conflation of the two concepts happens __only__ for custom services.
- For the services we are getting from svcat we have two different resources: `ServiceInstance`, and `ServiceBinding`.
- Research: Can a `ServiceBinding` be mounted into a pod/container, like a secret ?
  - If not, carrier has to translate the information in the binding into a secret which can.
  - If yes, then we should see what happens if we create our own binding for custom services, with no `ServiceInstance` behind them. Or if we can create a kind of instance which does not trigger an attempt by SVCat to provision it.

**Comment by jimmykarily** [comment]
@andreas-kupries I'm following the steps from [this video](https://youtu.be/bm59dpmMhAk?t=749) and when I bind a service with `svcat bind mysql` (mysql is a service instance I created before and is now ready), I see both a `ServiceBinding` and `Secret`  created. The ServiceBinding has a reference to the Secret.

From the user's perspective, after creation, the only difference between custom user provided services and provisioned ones is that when a service is deleted, in the case of the provisioned ones, they should be de-provisioned while for the custom ones we simply delete the relevant binding information. Other than that the 2 kind of services should behave the same (e.g. in regard to accessing the information from withing the app, binding to apps etc).

It may not be a good idea to create `ServiceBinding`s for our custom services since that a CRD monitored by the service catalog operator and we should better not mess with it. Using the Secret and the common backend for both kind of Services in Carrier leaves us with only naming conventions and maybe the use of some custom labels to distinguish between "service secrets" and other secrets. We also need some place to store the type of the Service (how it was created) so we know if we need to de-provision something or not and how (in case we have ways other than service catalog to provision services in the future).

I see 2 options:

1. We introduce a Service custom resource for Carrier to abstract the various services (no matter where they come from)
2. We rely on labels/annotations and some smart detection in Carrier code to be able to track where the Service came from (e.g. if there is a matching ServiceBinding that would be a service catalog type etc). When listing Service instances we would be listing Secrets with a specific label.

Option 2 seems simpler in the current state of things but could easily go out of hand. Option 1 will take a bit more to implement (defining CRDs and such) but we may get automated cleanups if we define ownership on the custom resource and connect it to the things created by service catalog.

Maybe it's worth checking for a well-known abstraction for Services, something like the [application crd](https://github.com/kubernetes-sigs/application) but for services. Or maybe the application crd is already suitable for services too?

**Comment by jimmykarily** [comment]
Option number 3, we can create a ConfigMap to act as the Service abstraction. It would be something like a poor mans CRD where we describe the Service in a structured way. The only good thing with this option is that it takes less time to implement compared to a service CRD. Not sure if I like it but I thought I should include it too.

**Comment by andreas-kupries** [comment]
I will collect some info about the svcat instance and binding resources, and their secrets ... Mainly what kind of labeling and annotations they contain ... Resulting writeups will be added here, plus thoughts on extending for carrier and custom services.

I wonder, is it possible add labels to any resource without the controlling operator being triggered ?
I know that annotations can change behaviour of a resource, so that it likely monitored by operators ...
More to read up on, i.e. differences between A's and L's in kube.

**Comment by andreas-kupries** [comment]
## SVcat info

- The instance and binding resources are namespaced. We provide the namespace.
- The secret for a binding is in the same namespace as the binding resource.
- svcat watches the entire cluster.
- We have full control over the names of instances, bindings, and associated secrets.
- The binding secrets store the information in the same manner as I specified custom services. I.e. a separate key and value per key in the binding info.

Examples
  1. Instance: [sv-instance.yaml.txt](https://github.com/SUSE/carrier/files/6042066/sv-instance.yaml.txt)
  2. Two bindings: [sv-binding.yaml.txt](https://github.com/SUSE/carrier/files/6042065/sv-binding.yaml.txt)

Note in the bindings how the name of the secret is specified.

## General kubernetes

  - Labels on resources contain only identifying information.
  - It is annotations which may contain more complex data and cannot contain identifying information (because you cannot search via them).

This means to me that adding or removing labels should not trigger behaviour in kubernetes, and we should be able to put labels on anything we want, including resources not fully under carrier's control, like SVCAT resources.

**Comment by andreas-kupries** [comment]
Updated design:

  1. All resources for a service S in organization O are named `service.((O)).((S))`.
  2. All resources for a binding of service S to application A, both in organization O are named `service.((O)).((S)).((A))`.
  3. For custom services the binding resources are copies of the service resource.
  4. All resources for a service S and its bindings are labeled `carrier/service=((type))` where `type` in { `svcat`, `custom` }.
  5. All resources for a service S and its bindings are labeled `carrier/service-name=S`.
  6. All binding resources for a service and app A are labeled `carrier/service-app=A`.

In the case of the secrets made by SVcat the labeling is done after the resource was created.
For all other resources the labels are part of the creation process.

**Comment by andreas-kupries** [comment]
## Examples

Application is A in workspace W.

### Custom service CS

  - Secret `service.oW.sCS` represents the service. Labels:
      - `carrier/service=custom`
      - `carrier/service-name=CS`
  - Secret `service.oW.sCS.aA` represents the binding of service to app.
      - `carrier/service=custom`
      - `carrier/service-name=CS`
      - `carrier/service-app=A`

### svcat service DB

  - ServiceInstance `service.oW.sDB` represents the service.
  - ServiceBinding `service.ow.sDB.aA` represents the binding
  - Secret `service.ow.sDB.aA` is also part of the binding.

**Comment by andreas-kupries** [comment]
And now I am wondering if it would be better to split the org app and service names into separate labels. ... That sould make search easier. Modifying the example for this yields:

  - Secret `service.oW.sCS` represents the service. Labels:
      - `carrier/service=custom`
      - `carrier/service-name=CS`
      - `carrier/service-org=W`
  - Secret `service.oW.sCS.aA` represents the binding of service to app. Labels:
      - `carrier/service=custom`
      - `carrier/service-name=CS`
      - `carrier/service-app=A`
      - `carrier/service-org=W`

  - ServiceInstance `service.oW.sDB` represents the service. Labels:
      - `carrier/service=custom`
      - `carrier/service-name=DB`
      - `carrier/service-org=W`
  - ServiceBinding `service.oW.sDB.aA` represents the binding. Labels:
      - `carrier/service=custom`
      - `carrier/service-name=DB`
      - `carrier/service-app=A`
      - `carrier/service-org=W`
  - Secret `service.oW.sDB.aA` is also part of the binding. Labels:
      - see above.

**Comment by andreas-kupries** [comment]
The common labels (See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ )
may fit in part. Not all, I believe.

I currently see

Label|Value|
|---|---|
|name| "carrier" |
|version| carrier version |
|component| "service", "binding", "bind-secret", ... |

And then come the custom labels to set service class ("svcat", "custom"), and the references to user app, org, and service name.
