### ISSUE TITLE
Is Traefik self signed cert good enough for dev?

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#178]
When the user doesn't have a domain, we use omg.howdoi.website magic dns. Somehow the applications deployed by Carrier are accessed only over `https`. This must be some self signed certificate created and used by the traefik deployment.

We need to find out how that works and if it is sufficient for development purposes or we need to implement something [like this](https://cert-manager.io/docs/configuration/selfsigned/)

We should also check, in the case where we don't install Traefik (but is already installed by the user), do they still get a self signed certificate? Is there a way to always have Traefik serving over https, even when we haven't installed Traefik ourselves.

**Comment by jimmykarily** [comment]
Although the applications are only served over `https`, after pushing we advertise the application url as `http` (we print a link that doesn't work). We need to change that as part of this story.

**Comment by rohitsakala** [comment]
1. Traefik allows only HTTPS traefik when this annotation `traefik.ingress.kubernetes.io/router.tls: true` is present on the ingress.
2. If the user/developer didn't specify a `self-signed certificate` like our case, traefik generates a default `self-signed certificate` with CN - `TRAEFIK DEFAULT CERTIFICATE` and serves it. This certificate is not stored in a Kubernetes secret. [0]

These are the reasons why our apps are served only on HTTPS. In short, because of the annotation.

Problems with Traefik approach
1. The self-signed certificate is not trusted by the browser. 
2. The self-signed certificate will always have the wrong CN.

Problems with Cert-Manager approach
1. The self-signed certificate is not trusted by the browser.

Advantages with Cert-Manager approach
1. The CN will have the correct name and so if we make the browser trust the CA authority of the self-signed certificate i.e itself, then the user will not face a `wrong CN name` error like in the Traefik approach.

So, I think the traefik approach is sufficient as anyways, the developer is going to use `-k` flag or click `proceed` button in the browser when the cert error is shown. 


[0] https://doc.traefik.io/traefik/https/tls/#default-certificate

- By default, traefik is installed by enabling three entry points out of which one is websecure (HTTPS). 
- If the user installs without websecure entrypoint, then the carrier app wouldn't work as the annotation  `traefik.ingress.kubernetes.io/router.tls: true` is present on the ingress carrier app. This means, our app takes only HTTPS traffic but traefik doesn't support HTTPS traffic as the entrypoint is disabled while installing.
- So, if the user installs, the carrier cannot guarantee that the app will work as of now.
