### ISSUE TITLE
Group service commands

### ISSUE THREAD

**Issue by thardeck** [SUSE/carrier#216]
Carrier does not group the service commands and has many different names.

We should group them together under a `carrier service` command.

## Acceptance criteria

* All carrier service commands are provided by `carrier service`
* There is an alias for `carrier services` -> e. g. `carrier service list`

**Comment by jimmykarily** [comment]
I suggest we treat both `services` and `service` as the same command (aliases). It's always very confusing when you have to remember which commands are in plural and which are singular.

**Comment by kkaempf** [comment]
We had the singular/plural discussion yesterday and agreed to use `carrier service ...` for all sub-commands and only `carrier services` as an abbreviation for `carrier service list`.

How's this handled in the kubernetes world (`kubectl`, `kubeadm`, ...) ?

**Comment by jimmykarily** [comment]
`kubectl` treats both plural and singular as the same command: `kubectl get pods` == `kubectl get pod` etc

**Comment by agracey** [comment]
https://github.com/kubernetes/kubernetes/issues/18622 Here's some discussion about pluralization.

Kubectl also expects the API/CRD maintainers to specify the pluralization for the CLI to pick up.

FWIW, I think having the `services` be an alias to `service list`  then also let `services <blah>` be aliased to `service <blah>` would be nice if it's not hard to do. The reason for this is just a reduction in typos for those of us who edit commands from history instead of retyping.
