### ISSUE TITLE
Use Kubernetes common labels for services created for carrier apps.

### ISSUE THREAD

**Issue by rohitsakala** [SUSE/carrier#218]
This is the remaining work to be done on issue #150. 
The task for this issue is to ensure that generic labels are put on carrier app services.

**Comment by andreas-kupries** [comment]
Notes ...

  - Putting labels on the `service instance` and `service binding` resources is, I believe simple. We are creating these resources, see `internal/services/catalog_service.go`, so we can add labels at will.
  - The secret generated by SV in response to us posting a `service binding` resource is a bit more complex. We have to wait for it to exist, and then can attach labels after the fact. We know what to wait for because we control the name of that secret. For the code we can use the existing function to label a namespace after the fact as an example.

  - Regarding the pods created by SV and backend broker in response to our `service instance`.
    I do not see that as possible for us. We have no control at all over the broker and/or the chart it uses. Actually even the fact that it does use a chart is suspect. True for minibroker. Very untrue for the google service broker. That one creates the service in google, likely completely outside of our cluster. IOW we have nothing to attach labels to. And that is likely the general situation for any broker.

   My personal recommendation is to have that last out of scope for carrier.

@kkaempf @jimmykarily :bell:

**Comment by jimmykarily** [comment]
I agree with the Andreas' last point. The whole tagging story started as a way to know what to delete when uninstalling Carrier. That was a way to know what things we deployed and thus belong to Carrier (there is always the argument that once something is installed on the cluster and accessible then it no longer belongs to you but that's another story). Let's not make tagging more important than the problem it originally tried to solve.

There are other ways to ensure proper cleanup (e.g. owner relationships). Let's tag what we create for now.
